name: Upload Image to S3 and Invoke Lambda
on:
  workflow_dispatch: # This allows you to manually trigger the workflow
permissions:
  contents: read
  id-token: write

jobs:
  upload-and-invoke:
    name: Upload Image to S3 and Invoke Lambda
    runs-on: ubuntu-latest

    steps:
      # Step: Checkout code (fetch repository content)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step: Set up AWS credentials via OIDC
      - name: Set up AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::677276078111:role/GithubActions-lambda-api-sso
          role-session-name: github-actions-session
          aws-region: us-east-1
          audience: sts.amazonaws.com

      # Step: Upload image to S3
      - name: Upload Image to S3
        run: |
          # Hardcoded values for the image and S3 bucket
          IMAGE_PATH="infra/environments/dev/johnsmith.jpg"
          BUCKET_NAME="buckettostoreemployeeimages"
          
          # Upload image to the S3 bucket
          aws s3 cp "$IMAGE_PATH" "s3://$BUCKET_NAME/$(basename $IMAGE_PATH)"
        env:
          AWS_REGION: us-east-1

      # Step: Invoke Lambda function
      - name: Invoke Lambda function
        run: |
          # Hardcoded values for the Lambda function and event file
          FUNCTION_NAME="greeting_lambda"
          EVENT_FILE_PATH="infra/environments/dev/event.json"
          
          # Invoke the Lambda function using the event file
          aws lambda invoke \
            --function-name "$FUNCTION_NAME" \
            --cli-binary-format raw-in-base64-out \
            --payload file://"$EVENT_FILE_PATH" \
            output.txt
        env:
          AWS_REGION: us-east-1
