name: Upload Image to S3 and Invoke Lambda
on:
  workflow_dispatch:
    inputs:
      image-path:
        description: "Path to the image to upload"
        required: true
        type: string
      s3-bucket:
        description: "S3 Bucket Name"
        required: true
        type: string
      lambda-function-name:
        description: "Lambda Function Name"
        required: true
        type: string
      event-file-path:
        description: "Path to the event JSON file for Lambda"
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  s3: write
  lambda: invoke

jobs:
  upload-and-invoke:
    name: Upload Image to S3 and Invoke Lambda
    runs-on: ubuntu-latest

    steps:
      # Step: Checkout code (if event.json is inside your repo)
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step: Set up AWS credentials via OIDC
      - name: Set up AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::677276078111:role/GithubActions-lambda-api-sso
          role-session-name: github-actions-session
          aws-region: us-east-1
          audience: sts.amazonaws.com

      # Step: Upload image to S3
      - name: Upload Image to S3
        run: |
          IMAGE_PATH="${{ github.event.inputs.image-path }}"
          BUCKET_NAME="${{ github.event.inputs.s3-bucket }}"
          aws s3 cp "$IMAGE_PATH" "s3://$BUCKET_NAME/$(basename $IMAGE_PATH)"
        env:
          AWS_REGION: us-east-1

      # Step: Invoke Lambda function
      - name: Invoke Lambda function
        run: |
          FUNCTION_NAME="${{ github.event.inputs.lambda-function-name }}"
          EVENT_FILE_PATH="${{ github.event.inputs.event-file-path }}"
          aws lambda invoke \
            --function-name "$FUNCTION_NAME" \
            --cli-binary-format raw-in-base64-out \
            --payload file://"$EVENT_FILE_PATH" \
            output.txt
        env:
          AWS_REGION: us-east-1
